import 'package:attendence_app/screens/committee/add_committee_member_screen.dart';
import 'package:attendence_app/screens/committee/add_employee_screen.dart';
import 'package:attendence_app/screens/committee/committee_dashboard_screen.dart';
import 'package:attendence_app/screens/committee/view_employee_attendance_screen.dart';
import 'package:attendence_app/screens/employee/employee_dashboard_screen.dart';
import 'package:attendence_app/screens/employee/mark_attendance_screen.dart';
import 'package:attendence_app/screens/employee/view_my_attendance_screen.dart';
import 'package:attendence_app/screens/initial_screen.dart';
import 'package:attendence_app/screens/login_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is typically generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Society Attendance',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        primaryColor: Colors.teal,
        hintColor: Colors.tealAccent,
        scaffoldBackgroundColor: const Color(0xFF121212),
        cardColor: const Color(0xFF1E1E1E),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.teal,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8.0),
            ),
            padding: const EdgeInsets.symmetric(
              vertical: 12.0,
              horizontal: 16.0,
            ),
          ),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF1E1E1E),
          elevation: 4.0,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 20.0,
            fontWeight: FontWeight.bold,
          ),
          iconTheme: IconThemeData(color: Colors.white),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF2C2C2C),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8.0),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8.0),
            borderSide: const BorderSide(color: Colors.tealAccent),
          ),
          labelStyle: const TextStyle(color: Colors.white70),
          hintStyle: const TextStyle(color: Colors.white54),
        ),
        textTheme: ThemeData.dark().textTheme.apply(
          bodyColor: Colors.white,
          displayColor: Colors.white,
        ),
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const InitialScreen(),
        '/login': (context) => const LoginScreen(),
        '/committee_dashboard': (context) => const CommitteeDashboardScreen(),
        '/add_committee_member': (context) => const AddCommitteeMemberScreen(),
        '/add_employee': (context) => const AddEmployeeScreen(),
        '/view_employee_attendance':
            (context) => const ViewEmployeeAttendanceScreen(),
        '/employee_dashboard':
            (context) => const EmployeeDashboardScreen(uname: ''),
        '/mark_attendance': (context) => const MarkAttendanceScreen(),
        '/view_my_attendance': (context) => const ViewMyAttendanceScreen(),
      },
    );
  }
}
